language: c

compiler:  
    - gcc
    - clang

before_script:  
    - mkdir build
    - cd build
    - cmake ..

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq hwloc cuda

script: make

