pipelines:
  default:
    - step:
        script:
          - echo "Mirroring repository to GitHub..."
          - mkdir -p ~/.ssh
          - (umask  077 ; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - git push git@github.com:RRZE-HPC/GHOST.git
          - echo "Building and testing GHOST..."
          - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_8.0.61-1_amd64.deb
          - dpkg -i cuda-repo-ubuntu1404_8.0.61-1_amd64.deb
          - add-apt-repository ppa:ubuntu-toolchain-r/test
          - apt-get update
          - apt-get install -y libhwloc-dev cuda-toolkit-8-0 libopenmpi-dev libgsl0-dev cmake openmpi-bin gcc-5 g++-5
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
          - mkdir build
          - cd build
          - cmake .. -DGHOST_STREAM_ARRAY_SIZE=1e6 -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_C_FLAGS=-Werror
          - make -j 10
          - make check
          - cd ..
          - mkdir build-no-cuda
          - cd build-no-cuda
          - cmake .. -DGHOST_STREAM_ARRAY_SIZE=1e6 -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_C_FLAGS=-Werror -DGHOST_USE_CUDA=OFF
          - make -j 10
          - make check
