pipelines:
  default:
    - step:
        script:
          - echo "Mirroring repository to GitHub..."
          - mkdir -p ~/.ssh
          - (umask  077 ; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - git push git@github.com:RRZE-HPC/GHOST.git
          - echo "Building and testing GHOST..."
          - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_8.0.61-1_amd64.deb
          - dpkg -i cuda-repo-ubuntu1404_8.0.61-1_amd64.deb
          - apt-get update
          - apt-get install -y libhwloc-dev cuda-toolkit-8-0 libopenmpi-dev libgsl0-dev cmake openmpi-bin
          - mkdir build
          - cd build
          - cmake .. -DGHOST_STREAM_ARRAY_SIZE=1e6 -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_C_FLAGS=-Werror
          - make -j
          - make check
