pipelines:
  default:
    - step:
        image: atlassian/default-image:2
        script:
          - echo "Mirroring repository to GitHub..."
          - mkdir -p ~/.ssh
          - (umask  077 ; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - git push git@github.com:RRZE-HPC/GHOST.git
          - echo "Building and testing GHOST..."
          - wget https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda_9.2.148_396.37_linux
          - sh cuda_9.2.148_396.37_linux
          - apt-get update
          - apt-get install -y libhwloc-dev libopenmpi-dev libgsl0-dev cmake openmpi-bin
          - mkdir build
          - cd build
          - cmake .. -DGHOST_STREAM_ARRAY_SIZE=1e6 -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_C_FLAGS=-Werror
          - make -j 10
          - make check
          - cd ..
          - mkdir build-no-cuda
          - cd build-no-cuda
          - cmake .. -DGHOST_STREAM_ARRAY_SIZE=1e6 -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_C_FLAGS=-Werror -DGHOST_USE_CUDA=OFF
          - make -j 10
          - make check
