pipelines:
  default:
    - step:
        script:
          - echo "Mirroring repository to GitHub..."
          - mkdir -p ~/.ssh
          - (umask  077 ; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - git push git@github.com:RRZE-HPC/GHOST.git